import streamlit as st
import pandas as pd
import datetime
#D:\OneDrive\Desktop\Projects\black-tiger-ma>streamlit run black-tiger-ma-v4.py
st.image("black-tiger-ma.jpg")
def login():
    selection = st.radio("Please choose Login or New User",
    [":rainbow[Login]", ":rainbow[New User]"])
    if selection == ":rainbow[Login]":
        st.title("Login")
        enterusername = st.text_input("Please enter email address to update system")
        enterpassword = st.text_input("Please enter password", type="password")
        if st.button("Check User"):
            file = open("black-tiger-ma.csv", "r", encoding="utf-8-sig")
            user_found = False
            for line in file:
                lines = line.strip().split(",")

                username = lines[0]
                password = lines[1]
                surname = lines[2]
                forename = lines[3]
                Grade = lines[5]
                GradingDate = lines[6]
                admin = lines[7]
                if enterusername == username and enterpassword == password and admin == "Y":
                    with open("black-tiger-ma-log.csv", "a", newline='') as file:
                        file.write(username + "," + str(datetime.datetime.now().replace(microsecond=0)) + "\n")                
                        st.session_state.logged_in = True
                        st.success("Login Successful")
                        user_found = True
                        break
                if enterusername == username and enterpassword == password and admin == "N":
                    with open("black-tiger-ma-log.csv", "a", newline='') as file:
                        file.write(username + "," + str(datetime.datetime.now().replace(microsecond=0)) + "\n")                
                        user_found = True
                        belts = ["4 Dan","3 Dan","2 Dan","1 Dan","Brown","Brown/White","Green","Green/White","Yellow","Yellow/White","Blue","Blue/White","Red","Red/White","White/Red","White"]
                        belt_index = belts.index(Grade)  
                        if belt_index > 0:  
                            nbelt = belts[belt_index - 1]
                        else:
                            nbelt = "You have achieved the highest belt"
                        st.write("Hi " + forename + " our records indicate you are a " + Grade + " belt." + " Your next belt is " + nbelt)
                        if Grade == "3 Dan":
                            st.subheader("4 Dan - Sandan: All basics from All Kyu Grades")                            
                            st.write("For grading: - Dan Grades are done in November of Each year.")
                            st.write("4 years as Sandan")
                            st.write("This is a partially technical grade as most candidates reaching this level would have spent many years practicing and possibly teaching everything in the syllabus already.")
                            #st.write("Hence why demonstration of the Basics is not required whereas a teaching knowledge is required. This is the last formal grading for this syllabus. All Further Gradings are Time awarded. ")                              st.subheader("3 Dan: Grapples")
                            st.write("Grappling Method – All Grappling Methods, Type 1 to Type 9")
                            st.write("All Throws and Groundwork")                         
                            st.subheader("4 Dan: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 6 direction (moves 1,2,3,4,5 and 6) for 1 minutes")                            
                            st.subheader("Kata")                            
                            st.write("Combat Kata 2")
                            st.write("All Kata from the syllabus continuous")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 30×1.5 minute rounds")
                            st.subheader("Bag Test")
                            st.write("10 minutes ‘bag work’ – 4 mins round kicks, 2 mins front kicks, 2 mins front punches, and 2 mins front punches/kicks") 
                        elif Grade == "2 Dan":
                            st.subheader("3 Dan - Nidan: All basics from All Kyu Grades")                            
                            st.write("For grading: - Dan Grades are done in November of Each year.")
                            st.write("3 years as Nidan")
                            st.write("This is a partially technical grade as most candidates reaching this level would have spent many years practicing and possibly teaching everything in the syllabus already. Hence why demonstration of the Basics is not required whereas a teaching knowledge is required. This is the last formal grading for this syllabus. All Further Gradings are Time awarded. ")                        
                            st.write("Take Class including basics for Kyu Grades and Dan Grades")
                            st.subheader("3 Dan: Grapples")
                            st.write("Grappling Method – All Grappling Methods, Type 1 to Type 9")
                            st.write("All Throws and Groundwork")                         
                            st.subheader("3 Dan: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 6 direction (moves 1,2,3,4,5 and 6) for 1 minutes")                            
                            st.subheader("Kata")                            
                            st.write("Brown Belt Kata 2")
                            st.write("All Kata from the syllabus and application of 4 Kata")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 30×1.5 minute rounds")
                            st.write("1 mile Run/Jog without stopping")
                            st.subheader("Bag Test")
                            st.write("10 minutes ‘bagwork’ – 4 mins round kicks, 2 mins front kicks, 2 mins front punches, and 2 mins front punches/kicks")                        
                        elif Grade == "1 Dan":
                            st.subheader("2 Dan - Shodan: All basics from All Kyu Grades")                            
                            st.write("For grading: - Dan Grades are done in November of Each year.")
                            st.write("2 years as Shodan")
                            st.write("All basics from All Kyu Grades")                        
                            st.subheader("2 Dan: Grapples")
                            st.write("Grappling Method – All Grappling Methods, Type 1 to Type 9")
                            st.write("All Throws and Groundwork, plus")
                            st.write("Nami-juji-jime (Normal cross strangle)")                            
                            st.write("Ude-hishigi-Sankaku-gatame (Triangular lock)")                            
                            st.write("Sode-guruma-jime (Sleeve wheel strangle)")                            
                            st.subheader("2 Dan: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 6 direction (moves 1,2,3,4,5 and 6) for 1 minutes")                            
                            st.subheader("Kata")                            
                            st.write("Tensho Kata")
                            st.write("All Kata from the syllabus and application of 3 Kata")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 25×1.5 minute rounds")
                            st.write("1 mile Run/Jog without stopping")
                            st.subheader("Bag Test")
                            st.write("10 minutes ‘bagwork’ – 4 mins round kicks, 2 mins front kicks, 2 mins front punches, and 2 mins front punches/kicks")                        
                            st.subheader("2 Dan: Throws")
                            st.write("Tani Otoshi: ‘Valley Drop’ (sacrifice throw)")
                            st.write("Morote gari (諸手刈, open arms reaping), or Udewa (腕輪, bracelet), ‘Arm Ring’")
                            st.write("Tsubame Gaeshi: ‘Swallow Reversal’")
                            st.write("Katawa Guruma: ‘Cripple Wheel’")
                        elif Grade == "Brown":                            
                            st.subheader("1 Dan - Shodan: Basics Number 10 Kihon KU")
                            st.write("For grading: - Dan Grades are done in November of Each year.")
                            st.write("Candidates must be 1st Kyu before the November of the previous year to be eligible")
                            st.write("12 months as 1st Kyu (or minimum of 4 ½ years training) or Junior Dan Grade/1st Kyu reaching age 16")
                            st.write("All basics from All Kyu Grades")                        
                            st.subheader("1 Dan: Grapples")
                            st.write("Grappling Method – All Grappling Methods, Type 1 to Type 9")
                            st.write("All Throws and Groundwork, plus")
                            st.write("Ashi-Hishigi (Achilles/Calf lock) )")
                            st.write("Gyaku-jiji-jime (Reverse cross strangle)")
                            st.write("Ude-hishigi-juji-gatame (Cross lock – Arm Bar)")
                            st.subheader("1 Dan: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 6 direction (moves 1,2,3,4,5 and 6) for 1 minutes")                            
                            st.subheader("Kata")
                            st.write("Black Belt Kata & all previous Kata")
                            st.write("Application of 2 previous Kata")                            
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 20×1.5 minute rounds")
                            st.write("1 mile Run/Jog without stopping")
                            st.subheader("Bag Test")
                            st.write("10 minutes ‘bag work’ – 4 mins round kicks, 2 mins front kicks, 2 mins front punches, and 2 mins front punches/kicks")                        
                            st.subheader("1 Dan: Throws")
                            st.write("O Soto gari (大外刈, major outer reaping))")
                            st.write("Harai Goshi (払腰): Sweeping hip throw")                            
                        elif Grade == "Brown/White":
                            st.subheader("Brown: Basics Number 10 Kihon KU")
                            st.subheader("For grading: - 6 months as 2nd Kyu")
                            st.write("All basic Pad work performed from ‘Fighting Stance’ Left Leg forward then right leg forward.")
                            st.write("Each performed 8 times (2x for both legs)")                            
                            st.write("Focus Mits – Jab, Cross, Hook, Uppercut, Front Kick, Side Kick, Back Kick, Round Kick")
                            st.write("Thai Pads – Jab, Cross, Hook, Uppercut, Front Kick, Side Kick, Back Kick, Round Kick.")    
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Fighting Stance’ Left Leg forward then right leg forward.")
                            st.write("Each performed 8 times (2x for both legs).")                            
                            st.write("Basic Kick 1 – Crescent kick to head, front leg then back leg")
                            st.write("Basic Kick 2 – Axe kick to head/collarbone, front leg then back leg")
                            st.write("Basic Kick 3 – Jumping side kick to ribs, front leg then back leg")
                            st.write("Basic Kick 4 – Jumping back kick to stomach, front leg then back leg")
                            st.write("Basic Kick 5 – Jumping back round kick to ribs, front leg then back leg")
                            st.write("Basic Kick 6 – Low Spinning Sweeping Kick")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Crescent kick to head off the front leg, step across, jumping back round kick off the Left leg, finish right leg forward. Alternative legs")
                            st.write("Jumping back round kick off the Left leg, Low Spinning Sweeping Kick finish right leg forward. Alternative legs")    
                            st.subheader("Brown: Grapples")
                            st.write("Grappling Method – Type 9")
                            st.write("Hadaka-jime (Naked strangle)")                            
                            st.subheader("Brown: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("•	Sabaki – 6 direction (moves 1,2,3,4,5 and 6) for 1 minutes")                            
                            st.subheader("Kata")
                            st.write("Brown Belt Kata & application & all previous Kata")                            
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 15×1.5 minute rounds")
                            st.subheader("Bag Test")
                            st.write("6 minutes ‘bag test’ – 2 mins axe kicks, 2 mins jumping back kicks, 2 mins jumping back kicks & jumping back round kicks")                        
                            st.subheader("Brown: Throws")
                            st.write("O uchi gari (大内刈, major inner reaping)")
                            st.write("Kibisu gaeshi (踵返, Ankle Pick")
                            st.write("Sangaku-jime (Triangular strangle)")                            
                        elif Grade == "Green":                            
                            st.subheader("Brown/White: Basics Number 9 Kihon KU")
                            st.subheader("Kicks")                            
                            st.write("All basic kicks performed from ‘Fighting Stance’ left leg forward then right leg forward. .")
                            st.write("Each performed 8 times (5x each leg for Basic kicks 3 & 4).")
                            st.write("Basic Kick 1 – Jumping knee strike, front leg then back leg.")
                            st.write("Basic Kick 2 – Front leg Hooking kick")
                            st.write("Basic Kick 3 – Rear Leg Cutting kick")
                            st.write("Basic Kick 4 – Jumping front kick to stomach, front leg then back leg")
                            st.write("Basic Kick 5 – Jumping round kick to stomach, front leg then back leg")
                            st.subheader("Kick combination, left and right leg forward")
                            st.write("Each performed 5 times")
                            st.write("Fighting stance, jumping front kick off the front leg, jumping round kick off the back leg, step forward, step back, and then step forward")
                            st.subheader("Brown/White: Grapples")
                            st.write("Grappling Method – Type 8")
                            st.write("Ude-hishigi-waki-gatame (Armpit lock)")
                            st.subheader("Brown/White: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 6 direction (moves 1,2,3,4,5 and 6) for 1 minutes")
                            st.subheader("Kata")
                            st.write("Brown Belt Kata & all previous Kata, Green Belt Kata application")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 8×1.5 minute rounds")
                            st.subheader("Bag Test")
                            st.write("2 mins jumping knees 2 mins jumping front kicks 2 mins jumping knees and jumping round kicks")                            
                            st.subheader("Brown/White: Throws")
                            st.write("Ko uchi gari (小内刈, minor inner reaping) – similar to Ashi Barai")
                            st.write("Tate-shiho-gatame (Straight four-corner hold)")
                        elif Grade == "Green/White":                            
                            st.subheader("Green: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Leopard hand to sternum, alternate hands.")
                            st.write("Basic strike 2 – Ridge hand to side of face, alternate hands.")
                            st.write("Basic strike 3 – Forearm strike to face alternate hands.")
                            st.write("Basic strike 4 – Tiger Claw Strike to face alternate hands.")                            
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times with left leg forward then right leg forward")
                            st.write("Fighting stance, Ridge hand to the side of the face off the front hand, forearm strike to face off the back hand with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Fighting Stance’ feet shoulder width apart.")                            
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 – Triangle kick (back leg only).")
                            st.write("Basic Kick 2 – Back round kick, Alternate legs")
                            st.write("Basic Kick 3 – Inside Round Kick, Front and Rear ")                            
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Triangle kick followed by Back Round Kick, left leg forward then right leg")                            
                            st.subheader("Green: Grapples")
                            st.write("Grappling Method – Type 7")
                            st.write("Ude-garame (entangled arm lock – Figure 4)")
                            st.subheader("Green: Evasion")                            
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 2 direction (moves 5 and 6) for 1 minutes")                            
                            st.subheader("Kata")                            
                            st.write("Green Belt Kata & application. & all previous Kata")                            
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 5×1.5 minute rounds")                            
                            st.subheader("Bag Test")                            
                            st.write("2 mins Ridge hand 2 mins Triangle kick 2 mins Forearm strikes & Back round kick")                            
                            st.subheader("Green: Throws")                            
                            st.write("Ippon Seoi Nage, One Handed Shoulder Throw")
                            st.write("Yoko-shiho-gatame (Side four-corner hold)")                            
                        elif Grade == "Yellow":
                            st.subheader("Green/White: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Round elbow strike top head, alternate elbows .")
                            st.write("Basic strike 2 – Back elbow strike to face, alternate elbows.")
                            st.write("Basic strike 3 – Back fist to the side of attacker’s face, alternate hands. (Parallel stance)")
                            st.write("Basic strike 4 – Spinning back fist to the front, alternate hands/stances.")                            
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Slide forward, Round elbow strike to the jaw off the front hand, Spinning back elbow to the face with a kiai.")
                            st.write("Slide forward, back fist to the face with the front hand, step forward and across, Spinning back fist punch to the face with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Fighting Stance’ feet shoulder width apart.")                            
                            st.write("Each performed 10 times (Kiai on 10).")                            
                            st.write("Basic Kick 1 – Stopping kick with front leg.")
                            st.write("Basic Kick 2 – Back kick to stomach, alternate back legs")                            
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Fighting stance, Stopping kick, front leg, and step across, look over the left shoulder, back kick off the back leg")
                            st.subheader("Green/White: Grapples")
                            st.write("Grappling Method – Type 6")
                            st.write("Kata Gatame (Shoulder hold)")
                            st.subheader("Green/White: Evasion")
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 2 direction (moves 3 and 4) for 1 minute")
                            st.subheader("Kata")
                            st.write("Green Belt Kata & application & all previous Kata")                            
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 5×1 minute rounds")
                            st.subheader("Bag Test")                            
                            st.write("2 mins each include techniques from basics above")                            
                            st.subheader("Green/White: Throws")
                            st.write("Uki Goshi (浮腰): Floating half-hip throw")
                        elif Grade == "Yellow/White":
                            st.subheader("Yellow: Basics")
                            st.subheader("Yellow: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Dropping knife hand to collar bone, alternate hands.")
                            st.write("Basic strike 2 – Dropping hammer fist to collar bone/nose, alternate hands.")
                            st.write("Basic Strike 3 – Round knife hand to neck, alternate hands.")
                            st.write("Basic strike 4 – Round hammer fist to side of head, alternate hands.")                            
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Fighting stance, slide forward, dropping hammer fist to nose off the front hand, and dropping knife hand strike to the neck off the back hand with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 – Round kick to the ribs, front leg then back leg, (alternate legs)")
                            st.write("Basic Kick 2 – Round kick to the head, front leg then back leg, (alternate legs)")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Round kick to Ribs off the back leg, step forward, round kick to the head of the back leg, step forward")
                            st.subheader("Yellow: Grapples")
                            st.write("Grappling Method – Type 5")
                            st.write("Kuzure-kesa-gatame (Modified scarf hold)")
                            st.subheader("Yellow: Evasion")
                            st.write("Performed from fighting stance, left leg forward")
                            st.write("Sabaki – 2 direction (moves 1 and 2) for 1 minute (Core Movement)")
                            st.subheader("Kata")    
                            st.write("Yellow Belt Kata & application & all previous Kata")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 3×1 minute rounds")
                            st.subheader("Bag Test")
                            st.write("2 mins hammer fist 2 mins round kicks ribs 2 mins knife hand and round kicks head")                            
                            st.subheader("Yellow: Throws")
                            st.write("Sukui Nage (掬い投, Scooping Throw) Front Stance")
                        elif Grade == "Blue":
                            st.subheader("Yellow/White: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Knife hand block across, move back to start’")
                            st.write("Block 2 - ’Rising knife hand to the left’")
                            st.write("Block 3 – ‘Rising elbow block, covering with back hand’ ")                            
                            st.subheader("Yellow/White: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Palm heel strike to the head.")
                            st.write("Basic strike 2 – Palm heel strike to the ribs.")                            
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Fighting Stance, Palm heel strike to the head with the front hand, step forward and across, Palm heel strike to the ribs with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 – Knee joint kick, alternate legs.")
                            st.write("Basic Kick 2 – Side kick to stomach, alternate legs")                            
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Fighting stance, Knee joint kick off the front leg, side kick to the stomach off the back leg, step forward, step back")
                            st.subheader("Yellow/White: Grapples")
                            st.write("Grappling Method – Type 4")
                            st.write("Kesa-gatame (Scarf hold)")
                            st.subheader("Kata")
                            st.write("Yellow Belt Kata & Application & all previous Kata")                            
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 3×1 minute rounds")
                            st.subheader("Bag Test")
                            st.write("2 mins teach include techniques from basics above (with Thai Pads)")                            
                            st.subheader("Yellow/White: Throws")
                            st.write("Deashi barai (足掃, foot sweep) ")
                        elif Grade == "Blue/White":
                            st.subheader("Blue: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Front hand Rising block/Hooking block’")
                            st.write("Block 2 - ’Rising cross block’")
                            st.write("Block 3 – ‘Dropping cross block’ ")                          
                            st.subheader("Blue: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Round punch to the head.")
                            st.write("Basic strike 2 – Round punch to the ribs.")                            
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Round punch to the head off the front hand, round punch to the ribs off the back hand with a kiai.")                            
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Inside thigh kick with front leg.")
                            st.write("Basic Kick 2 – Outside thigh kick with back leg")                            
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Inside thigh kick off the front leg, foot down, outside thigh kick off the back leg, step forward, step back")
                            st.subheader("Blue: Grapples")
                            st.write("Grappling Method – Type 3")
                            st.subheader("Kata")
                            st.write("Blue Belt Kata & Application & all previous Kata")                            
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 3×1 minute rounds")
                            st.subheader("Bag Test")
                            st.write("2 mins teach include techniques from basics above (with Thai Pads)")                            
                            st.subheader("Blue/White: Throws")
                            st.write("Kubi Nage / Kubi Wa: ‘Neck Ring’ / neck throw")                           
                        elif Grade == "Red":
                            st.subheader("Blue/White: Basics")
                            st.write("First 2 blocks in parallel stance, last 2 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 6 times")
                            st.write("Block 1 - ‘Inside to Outside Block’")
                            st.write("Block 2 - ’Outside to Inside Block’")
                            st.write("Block 3 – ‘Front foot ‘Shin block’ across’ ")
                            st.write("Block 4 – ‘Front, then rear foot ‘Shin block’ to the front, Alternating legs’ ")
                            st.subheader("Blue/White: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Close punch (Uppercut) rising to chin, alternate hands.")
                            st.write("Basic strike 2 – Close punch to the stomach, alternate hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Kiai on very last punch - left leg then right leg forward")
                            st.write("Uppercut front hand, followed by Shovel Punch to the ribs of the back hand.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 – Groin kick, toes pointing forward alternative legs.")
                            st.write("Basic Kick 2 – Front kick to stomach, toes pulled back, alternative legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Groin kick to the stomach of the front leg, Front kick to the stomach of the back leg, step forward then repeat opposite side 3 forward Mawatte 3 back then Mawatte to front")
                            st.subheader("Blue/White: Grapples")
                            st.write("Grappling Method – Type 2")
                            st.subheader("Kata")
                            st.write("Blue Belt Kata & previous Kata (Juniors), plus application for Seniors")
                            st.write("Red Belt Kata application for Juniors")
                            st.subheader("Blue/White: Sparring")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.write("Sparring 3×1 minute rounds")
                            st.subheader("Bag Test")
                            st.write("2 mins punching, 2 mins front kicks, 2 mins punching and front kicks")
                            st.subheader("Blue/White: Breakfalls")
                            st.write("Forward Roll, Previous Breakfalls")
                        elif Grade == "Red/White":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Red: Breakfalls")
                            st.write("Forward, Back and Side (Left and Right)")
                            st.write("Technical Standup")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif Grade == "White/Red":
                            st.subheader("Red/White: Basics")
                            st.write("As previous grades")
                            st.subheader("Red/White: Strikes")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.subheader("Red/White: Bag test")
                            st.write("2 mins punching")
                            st.subheader("Red/White: Breakfalls")
                            st.write("As previous grades")
                        elif Grade == "White":
                            st.subheader("White/Red: Basics")
                            st.write("All 3 basic stances left leg forward then right leg forward.")
                            st.write("Each performed 5 times.")
                            st.write("Stance 1 - Ready - Parallel stance")
                            st.write("Stance 2 - Fighting stance")
                            st.write("Stance 3 – Mawatte turning")
                            st.subheader("Basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Performed 5 times. Palm Heel Block")
                            st.subheader("White/Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Making a Fist, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")
                            st.write("Basic Strike 3 – Punches to the face, alternative hands.")
                            st.subheader("White/Red: Breakfalls")
                            st.write("Forward, Back and Side (Left and Right)")
                            st.subheader("All answers performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("What is the Name of this Club? – Black Tiger Martial Arts")
                            st.write("What are the Styles of this Club? - Urban Tiger Kempo, Japanese Kickboxing and TaiChi")
                            st.write("What is the Name of the Senior Instructor? – Shihan Ken")
                            st.write("What are the Names of the Instructors – Shihan Ken, Sensei Stewart, Sensei Gabriel, Sempai Deanna, Sempai Jacob, Sempai Steve, Sempai Frank, Sempai Grandad, and Hanshi Wayne")
                            st.write("What are the Numbers 1 – 10 in Japanese? – Ichi, Ni, San, Shi, Go, Roku, Shichi, Hachi, Ku, Ju")
                        else:
                            st.subheader("White/Red: Basics")
                            st.write("All 3 basic stances left leg forward then right leg forward.")
                            st.write("Each performed 5 times.")
                            st.write("Stance 1 - Ready - Parallel stance")
                            st.write("Stance 2 - Fighting stance")
                            st.write("Stance 3 – Mawatte turning")
                            st.subheader("Basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Performed 5 times. Palm Heel Block")
                            st.subheader("White/Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Making a Fist, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")
                            st.write("Basic Strike 3 – Punches to the face, alternative hands.")
                            st.subheader("White/Red: Breakfalls")
                            st.write("Forward, Back and Side (Left and Right)")
                            st.subheader("All answers performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("What is the Name of this Club? – Black Tiger Martial Arts")
                            st.write("What are the Styles of this Club? - Urban Tiger Kempo, Japanese Kickboxing and TaiChi")
                            st.write("What is the Name of the Senior Instructor? – Shihan Ken")
                            st.write("What are the Names of the Instructors – Shihan Ken, Sensei Stewart, Sensei Gabriel, Sempai Deanna, Sempai Jacob, Sempai Steve, Sempai Frank, Sempai Grandad, and Hanshi Wayne")
                            st.write("What are the Numbers 1 – 10 in Japanese? – Ichi, Ni, San, Shi, Go, Roku, Shichi, Hachi, Ku, Ju")
                        break              
            if not user_found:
                st.error("Invalid username or password")
            file.close()
    else:
        st.title("New User")
        username = st.text_input("Please enter email to add user")
        password = st.text_input("Please enter password for user", type="password")
        surname = st.text_input("Please enter surname")
        forename = st.text_input("Please enter forename")
        DOB = st.date_input("Please enter date of birth", format="DD/MM/YYYY")
        grade = st.selectbox("Please current grade",
        ("3 Dan","2 Dan","1 Dan","Brown","Brown/White","Green","Green/White","Yellow","Yellow/White","Blue","Blue/White","Red","Red/White","White/Red","White"))
        GradingDate = st.date_input("Please enter last grading date", format="DD/MM/YYYY")
        if st.button("Add User"):
            with open("black-tiger-ma.csv", "a", newline='') as file:
                file.write(username + "," + password + "," + surname + "," + forename + "," + str(DOB) + "," + str(grade) + "," + str(GradingDate) + "," + "N" + "\n")        
def dashboard():
    st.write("Welcome Admin")
    if st.button("Sign Out"):
        st.session_state.logged_in = False
    st.title("User Management and Login Record")
    choice = st.radio("Please select add or remove",
    [":rainbow[Add]", ":rainbow[Remove]",  ":rainbow[Promote]",":rainbow[View]"])
    if choice == ":rainbow[Add]":
        username = st.text_input("Please enter email to add user")
        password = st.text_input("Please enter password for user", type="password")
        surname = st.text_input("Please enter surname")
        forename = st.text_input("Please enter forename")
        DOB = st.date_input("Please enter date of birth", format="DD/MM/YYYY")
        grade = st.selectbox("Please current grade",
        ("3 Dan","2 Dan","1 Dan","Brown","Brown/White","Green","Green/White","Yellow","Yellow/White","Blue","Blue/White","Red","Red/White","White/Red","White"))
        GradingDate = st.date_input("Please enter last grading date", format="DD/MM/YYYY")
        if st.button("Add User"):
            with open("black-tiger-ma.csv", "a", newline='') as file:
                file.write(username + "," + password + "," + surname + "," + forename + "," + str(DOB) + "," + str(grade) + "," + str(GradingDate) + "," + "N" + "\n")
    elif choice == ":rainbow[Remove]":
        username = st.text_input("Please enter username to remove")
        if st.button("Remove User"):
            df = pd.read_csv("black-tiger-ma.csv")
            if username in df["username"].values:
                df = df[df["username"] != username]
                df.to_csv("black-tiger-ma.csv", index=False)
                st.success(f"User {username} removed successfully.")
            else:
                st.error(f"Username {username} not found in the data.")
    elif choice == ":rainbow[Promote]":
        username = st.text_input("Please enter username to promote")
        df = pd.read_csv("black-tiger-ma.csv")
        if username in df["username"].values:
            grade = st.selectbox("Please select the current grade",
            ("3 Dan","2 Dan","1 Dan","Brown","Brown/White","Green","Green/White","Yellow","Yellow/White","Blue","Blue/White","Red","Red/White","White/Red","White"))
            GradingDate = st.date_input("Please enter the last grading date", format="DD/MM/YYYY")
            if st.button("Promote User"):
                # Update the user's grade and grading date
                df.loc[df["username"] == username, "Grade"] = grade
                df.loc[df["username"] == username, "GradingDate"] = GradingDate         
                # Save the updated DataFrame back to the CSV file
                df.to_csv("black-tiger-ma.csv", index=False)         
                st.success(f"User {username} has been promoted to {grade} with grading date {GradingDate}")
        else:
            st.error("Username not found")
    else:
        df = pd.read_csv("black-tiger-ma.csv")
        st.dataframe(df)
        df = pd.read_csv("black-tiger-ma-log.csv")
        st.dataframe(df)
        
if "logged_in" not in st.session_state:
    st.session_state.logged_in=False

if st.session_state.logged_in:
    dashboard()
else:
    login()






