import streamlit as st
import pandas as pd
import datetime
#D:\OneDrive\Desktop\Projects\black-tiger-ma>streamlit run black-tiger-ma-v4.py
st.image("black-tiger-ma.jpg")
def login():
    selection = st.radio("Please choose Login or New User",
    [":rainbow[Login]", ":rainbow[New User]"])
    if selection == ":rainbow[Login]":
        st.title("Login")
        enterusername = st.text_input("Please enter email address to update system")
        enterpassword = st.text_input("Please enter password", type="password")
        if st.button("Check User"):
            file = open("black-tiger-ma.csv", "r", encoding="utf-8-sig")
            user_found = False
            for line in file:
                lines = line.strip().split(",")

                username = lines[0]
                password = lines[1]
                surname = lines[2]
                forename = lines[3]
                Grade = lines[5]
                GradingDate = lines[6]
                admin = lines[7]
                if enterusername == username and enterpassword == password and admin == "Y":
                    with open("black-tiger-ma-log.csv", "a", newline='') as file:
                        file.write(username + "," + str(datetime.datetime.now().replace(microsecond=0)) + "\n")                
                        st.session_state.logged_in = True
                        st.success("Login Successful")
                        user_found = True
                        break
                if enterusername == username and enterpassword == password and admin == "N":
                    with open("black-tiger-ma-log.csv", "a", newline='') as file:
                        file.write(username + "," + str(datetime.datetime.now().replace(microsecond=0)) + "\n")                
                        user_found = True
                        belts = ["4 Dan","3 Dan","2 Dan","1 Dan","Brown","Brown/White","Green","Green/White","Yellow","Yellow/White","Blue","Blue/White","Red","Red/White","White/Red","White"]
                        GradeI = int(Grade) + 3
                        GradeN = int(Grade) + 2
                        belt = belts[GradeI]
                        nbelt = belts[GradeN]
                        st.write("Hi " + forename + " our records indicate you are a " + belt + " belt." + " Your next belt is " + nbelt)
                        st.write("You are a " + Grade + " kyu")
                        if belt == "3 Dan":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "2 Dan":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "1 Dan":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Brown":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")                  
                        elif belt == "Brown/White":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Green":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Green/White":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Yellow":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Yellow/White":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Blue":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Blue/White":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Red":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "Red/White":
                            st.subheader("Red: Basics")
                            st.write("All 3 basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Each performed 5 times")
                            st.write("Block 1 - ‘Palm Heel Block’")
                            st.write("Block 2 - ’Downward Block’")
                            st.write("Block 3 – ‘Rising Block’ ")
                            st.subheader("Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Punches to the face, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")    
                            st.subheader("Punching combination")
                            st.write("Each performed 5 times")
                            st.write("Front hand punch to the face, back hand punch to the stomach with a kiai.")
                            st.subheader("Kicks")
                            st.write("All basic kicks performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10).")
                            st.write("Basic Kick 1 –Knee strikes to the head alternative legs.")
                            st.write("Basic Kick 2 – Round knee strikes to the ribs – Alternative Legs")
                            st.subheader("Kick combination")
                            st.write("Each performed 5 times")
                            st.write("Front Knee, then back Round knee strikes")
                            st.subheader("Red: Grapples")
                            st.write("Grappling Method – Type 1")
                            st.subheader("Kata")
                            st.write("Red Belt for Juniors / Blue Belt for Seniors")
                        elif belt == "White/Red":
                            st.subheader("Red/White: Basics")
                            st.write("As previous grades")
                            st.subheader("Red/White: Strikes")
                            st.write("Shadow Sparring for 1 minute – include techniques from basics above")
                            st.subheader("Red/White: Bag test")
                            st.write("2 mins punching")
                            st.subheader("Red/White: Breakfalls")
                            st.write("As previous grades")
                        elif belt == "White":
                            st.subheader("White/Red: Basics")
                            st.write("All 3 basic stances left leg forward then right leg forward.")
                            st.write("Each performed 5 times.")
                            st.write("Stance 1 - Ready - Parallel stance")
                            st.write("Stance 2 - Fighting stance")
                            st.write("Stance 3 – Mawatte turning")
                            st.subheader("Basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Performed 5 times. Palm Heel Block")
                            st.subheader("White/Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Making a Fist, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")
                            st.write("Basic Strike 3 – Punches to the face, alternative hands.")
                            st.subheader("White/Red: Breakfalls")
                            st.write("Forward, Back and Side (Left and Right)")
                            st.subheader("All answers performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("What is the Name of this Club? – Black Tiger Martial Arts")
                            st.write("What are the Styles of this Club? - Urban Tiger Kempo, Japanese Kickboxing and TaiChi")
                            st.write("What is the Name of the Senior Instructor? – Shihan Ken")
                            st.write("What are the Names of the Instructors – Shihan Ken, Sensei Stewart, Sensei Gabriel, Sempai Deanna, Sempai Jacob, Sempai Steve, Sempai Frank, Sempai Grandad, and Hanshi Wayne")
                            st.write("What are the Numbers 1 – 10 in Japanese? – Ichi, Ni, San, Shi, Go, Roku, Shichi, Hachi, Ku, Ju")
                        else:
                            st.subheader("White/Red: Basics")
                            st.write("All 3 basic stances left leg forward then right leg forward.")
                            st.write("Each performed 5 times.")
                            st.write("Stance 1 - Ready - Parallel stance")
                            st.write("Stance 2 - Fighting stance")
                            st.write("Stance 3 – Mawatte turning")
                            st.subheader("Basic Blocks performed from ‘Fighting stance’ left leg forward then right leg forward.")
                            st.write("Performed 5 times. Palm Heel Block")
                            st.subheader("White/Red: Strikes")
                            st.write("All basic strikes performed from ‘Parallel stance’ feet shoulder width apart.")
                            st.write("Each performed 10 times (Kiai on 10)")
                            st.write("Basic Strike 1 – Making a Fist, alternative hands.")
                            st.write("Basic strike 2 – Punches to the sternum, alternative hands.")
                            st.write("Basic Strike 3 – Punches to the face, alternative hands.")
                            st.subheader("White/Red: Breakfalls")
                            st.write("Forward, Back and Side (Left and Right)")
                            st.subheader("All answers performed from ‘Parallel Stance’ feet shoulder width apart.")
                            st.write("What is the Name of this Club? – Black Tiger Martial Arts")
                            st.write("What are the Styles of this Club? - Urban Tiger Kempo, Japanese Kickboxing and TaiChi")
                            st.write("What is the Name of the Senior Instructor? – Shihan Ken")
                            st.write("What are the Names of the Instructors – Shihan Ken, Sensei Stewart, Sensei Gabriel, Sempai Deanna, Sempai Jacob, Sempai Steve, Sempai Frank, Sempai Grandad, and Hanshi Wayne")
                            st.write("What are the Numbers 1 – 10 in Japanese? – Ichi, Ni, San, Shi, Go, Roku, Shichi, Hachi, Ku, Ju")
                        break              
            if not user_found:
                st.error("Invalid username or password")
            file.close()
    else:
        st.title("New User")
        username = st.text_input("Please enter email to add user")
        password = st.text_input("Please enter password for user", type="password")
        surname = st.text_input("Please enter surname")
        forename = st.text_input("Please enter forename")
        DOB = st.date_input("Please enter date of birth", format="DD/MM/YYYY")
        grade = st.selectbox("Please current grade",
        (1,2,3,4,5,6,7,8,9,10,11,12,"1 Dan","2 Dan","3 Dan","4 Dan"))
        GradingDate = st.date_input("Please enter last grading date", format="DD/MM/YYYY")
        if st.button("Add User"):
            with open("black-tiger-ma.csv", "a", newline='') as file:
                file.write(username + "," + password + "," + surname + "," + forename + "," + str(DOB) + "," + str(grade) + "," + str(GradingDate) + "," + "N" + "\n")        
def dashboard():
    st.write("Welcome Admin")
    if st.button("Sign Out"):
        st.session_state.logged_in = False
    st.title("User Management and Login Record")
    choice = st.radio("Please select add or remove",
    [":rainbow[Add]", ":rainbow[Remove]",  ":rainbow[Promote]",":rainbow[View]"])
    if choice == ":rainbow[Add]":
        username = st.text_input("Please enter email to add user")
        password = st.text_input("Please enter password for user", type="password")
        surname = st.text_input("Please enter surname")
        forename = st.text_input("Please enter forename")
        DOB = st.date_input("Please enter date of birth", format="DD/MM/YYYY")
        grade = st.selectbox("Please current grade",
        (1,2,3,4,5,6,7,8,9,10,11,12,"1 Dan","2 Dan","3 Dan","4 Dan"))
        GradingDate = st.date_input("Please enter last grading date", format="DD/MM/YYYY")
        if st.button("Add User"):
            with open("black-tiger-ma.csv", "a", newline='') as file:
                file.write(username + "," + password + "," + surname + "," + forename + "," + str(DOB) + "," + str(grade) + "," + str(GradingDate) + "," + "N" + "\n")
    elif choice == ":rainbow[Remove]":
        username = st.text_input("Please enter username to remove")
        if st.button("Remove User"):
            df = pd.read_csv("black-tiger-ma.csv")
            if username in df["username"].values:
                df = df[df["username"] != username]
                df.to_csv("black-tiger-ma.csv", index=False)
                st.success(f"User {username} removed successfully.")
            else:
                st.error(f"Username {username} not found in the data.")
    elif choice == ":rainbow[Promote]":
        username = st.text_input("Please enter username to promote")
        df = pd.read_csv("black-tiger-ma.csv")
        if username in df["username"].values:
            grade = st.selectbox("Please select the current grade",
            (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "1 Dan", "2 Dan", "3 Dan", "4 Dan"))
            GradingDate = st.date_input("Please enter the last grading date", format="DD/MM/YYYY")
            if st.button("Promote User"):
                # Update the user's grade and grading date
                df.loc[df["username"] == username, "Grade"] = grade
                df.loc[df["username"] == username, "GradingDate"] = GradingDate         
                # Save the updated DataFrame back to the CSV file
                df.to_csv("black-tiger-ma.csv", index=False)         
                st.success(f"User {username} has been promoted to {grade} with grading date {GradingDate}")
        else:
            st.error("Username not found")
    else:
        df = pd.read_csv("black-tiger-ma.csv")
        st.dataframe(df)
        df = pd.read_csv("black-tiger-ma-log.csv")
        st.dataframe(df)
        
if "logged_in" not in st.session_state:
    st.session_state.logged_in=False

if st.session_state.logged_in:
    dashboard()
else:
    login()


